# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27967d0d0708de6d9cab38b9493cef5dbea99469a0932b3f7b331ae7591c9b43acdbb800947fd9a6f6f12116430534f0a5bd1570df9c42955b366fde7618d29e

test:
  secret_key_base: 1376d1ecebc90e0b6fc477007206fab5e8c7187d21e9bfd7be32d421964e1c2bf114ee1dc5b33c2e5b2cc9bbad66c3a5ffcf1bb408b3851aef41e663c4b0f394

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
